# @package _global_

dataset_name: zju_377_mono

dataset:
  name: refined_zjumocap
  # root_dir: "../../data/ZJUMoCap"
  root_dir: /home/disk/work/zychen/datasets/zjumocap
  subject: CoreView_377
  refine: false

  train_views: [ '00' ]
  val_views: ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22']
  test_views:
    view: ${dataset.val_views}
    video: ['12']
    all: []
  predict_views: ['00']

  train_frames: [ 0, 570, 1 ]
  val_frames: [ 0, 1, 1 ]
  test_frames:
    view: [0, 570, 30]
    video: [0, 570, 1]
    all: [0, 570, 1]
  predict_frames: [0, 0, 1]

  img_hw:
    - 512
    - 512

  lanczos: false
  resolution: -1
  white_background: false
  data_device: cuda
  eval: false