# @package _global_

dataset_name: zju_377_mono

dataset:
  name: refinezjumocap
  root_dir: ".datasets/zjumocap"
  subject: my_377
  refine: false

  train_views: [ '00' ]
  val_views: ['00']


  train_frames: [0, 100, 10]  #[ 0, 570, 1 ]
  val_frames: [ 0, 1, 1 ]


  img_hw:
    - 512
    - 512

  pca_components: 0  # 0 means no PCA

  lanczos: false
  resolution: -1
  white_background: false
  data_device: cuda
  device: cuda
  padding: 0.1
  eval: false