# @package _global_

dataset_name: zju_377_mono

dataset:
  name: zjumocap
  root_dir: ".datasets/zjumocap"
  subject: my_377
  refine: false

  train_views: [ '00' ]
  val_views: ['01', '02']
  test_views:
    view: ${dataset.val_views}
    video: ['12']
    all: []
  predict_views: ['1']

  train_frames: [ 0, 570, 1 ]
  val_frames: [ 0, 1, 1 ]
  test_frames:
    view: [0, 570, 30]
    video: [0, 570, 1]
    all: [0, 570, 1]
  predict_frames: [0, 0, 1]

  img_hw:
    - 512
    - 512

  lanczos: false
  resolution: -1
  white_background: false
  data_device: cuda
  eval: false